### ISSUE TITLE
lat long reference point

### ISSUE THREAD

**Issue by saeedarabi92** [fixposition/fixposition_driver#10]
Is there anyway to specify a lat and long reference point and calculate the Odometry based on that?

**Comment by fixposition-support** [comment]
Hello @saeedarabi92,

unfortunately the ref point cannot be specified as of now. We will add this feature into consideration.

**Comment by souryavarenya** [comment]
Hi @saeedarabi92, I am closing this issue as this doesn't pertain to the driver anymore. 

---

In case you're interested in implementing this at your end, we would be able to recommend using this ROS library - [geodetic_utils](https://github.com/ethz-asl/geodetic_utils/tree/master). Here's a snippet for your reference:

```cpp
#include <geodetic_utils/geodetic_conv.hpp>

//...

GeodeticConverter converter;
converter.initialiseReference(LAT_REF, LON_REF, ALT_REF);

double lat, lon, alt; // Retreive from our driver...

double e, n, u;
converter.geodetic2Enu(lat, lon, alt, &e, &n, &u)


```

---

We're currently also working on a feature for the sensor to natively publish ENU output in a provided reference frame. Keep an eye out for new software releases in the horizon of 1-2 months.
