### ISSUE TITLE
Retrieve PPS signal

### ISSUE THREAD

**Issue by Mikehuntisbald** [fixposition/fixposition_driver#26]
Hi, I would like to use v-RTK's PPS signal as the input of our PTP master for time sync. But after searching the internet, I found no infiormation on how to output PPS signal from the v-RTK. Could you please provide any help on this?

**Comment by Jelvon** [comment]
Hello

In Section 5.2.6 of our Integration Manual, we provide detailed instructions on configuring VRTK2 to output a PPS (Pulse Per Second) signal for time synchronization. You can access the manual through the following link:

https://docs.fixposition.com/fd/integration-manual

Please note that the PPS signal can be accessed from the I/O connector via pins 5 and 6.

If you need further clarification, we are more than happy to arrange a meeting to discuss this in detail. Please share your availability, and we will do our best to accommodate your schedule.

Best regards,

**Comment by Mikehuntisbald** [comment]
> Hello
> 
> In Section 5.2.6 of our Integration Manual, we provide detailed instructions on configuring VRTK2 to output a PPS (Pulse Per Second) signal for time synchronization. You can access the manual through the following link:
> 
> https://docs.fixposition.com/fd/integration-manual
> 
> Please note that the PPS signal can be accessed from the I/O connector via pins 5 and 6.
> 
> If you need further clarification, we are more than happy to arrange a meeting to discuss this in detail. Please share your availability, and we will do our best to accommodate your schedule.
> 
> Best regards,

Thank you very much. Now we have set up the sync system. May I also ask the baud rate of the ToD signal(Pin 6)?

Regards
