### ISSUE TITLE
Raw YPR output

### ISSUE THREAD

**Issue by grizzi** [fixposition/fixposition_driver#28]
### Description

Dear FP team, we have been trying to use the raw YPR estimate that the sensor should output at all times.  
The [documentation mentions](https://github.com/fixposition/fixposition_driver/blob/main/README.md?plain=1#L148) that its output is at 200HZ and that is published even prior to fusion. Nevertheless, when I connect the sensor (without antennas, table top setup) this topic is not actually published. 

### 
A quick inspection in the driver (ROS1) shows that the message conent [is parsed from the TF message](https://github.com/fixposition/fixposition_driver/blob/main/fixposition_driver_ros1/src/fixposition_driver_node.cpp#L134-L152), which is published at no more than 10Hz. 

### System Specs
**Hardware version**:  fp-957716 (nav-vr2 1.2b)
**Firmware version**:  fp_release_vr2_2.63.3_227
**Driver version**: main (commit [edaeb8e](https://github.com/fixposition/fixposition_driver/commit/edaeb8e71895cdc182f25e90833442d302030807))
**ROS version**: ROS1

**Comment by grizzi** [comment]
I have find out that the stream is not enabled when that is not selected in the sensor configuration. A possible enhancement is to add this information to the current readme as at the moment it sound like all topics should be available by default.  

![image](https://github.com/fixposition/fixposition_driver/assets/26412496/0b5d32c9-712a-4e35-b6ec-4574a3b071e5)

**Comment by fixposition-support** [comment]
@grizzi We're glad that your problem is solved. Also thank you for the suggestion, we'll update the readme and user manual soon.

**Comment by AngeLoGa** [comment]
Would like to open this issue again, was the user manual updated at last? Because I had this exact problem, and I didn't see any information regarding this. Sorry if I'm not correct.
