### ISSUE TITLE
Odometry Converter ROS 2

### ISSUE THREAD

**Issue by macstepien** [fixposition/fixposition_driver#33]
Hi,
I wanted to ask when do you plan to release the Odometry Converter for ROS 2? As I will need it quite soon, and it won't be much work to port it, I can also do it and create a PR if you would like.
Best regards,
Maciej

**Comment by fixposition-support** [comment]
Hi macstepien,

we are aware that this is currently only in ROS and not in ROS2. As we are at the moment mostly busy with other tasks, porting this to ROS2 is not a priority for now. If you would like to do it and create a PR we are more than happy and thankful for your contribution!

Best,
Kailin
