### ISSUE TITLE
Bloom release?

### ISSUE THREAD

**Issue by emersonknapp** [fixposition/fixposition_driver#39]
Hi maintainers, this package would be much easier to use if it was released via bloom into the ros buildfarm, and so could be installed via `apt`. Perhaps you'd be willing to do this?

For reference
http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease

**Comment by souryavarenya** [comment]
Hi @emersonknapp, 

Unfortunately given the use cases, and ease of incorporating a ROS package into a workspace, we're unable to commit workforce to release and maintain this. If we ever see more demand, we will update this thread. For now, I will close this issue.
