### ISSUE TITLE
Tag data incompatibility with latest version of driver

### ISSUE THREAD

**Issue by iamrajee** [fixposition/fixposition_driver#49]
While performing testing  `str2str -in file://vrtk2_output_1.txt::T -out tcpsvr://localhost:21000` with the latest v.6.1.4 gives the below parsing error:
```
Error in parsing TF string with 12 fields! TF will be empty.
Error in parsing Odometry string with 44 fields! Odometry and status messages will be empty.
```

Though the same dataset works fine with v.5.0.0. Is there a way to parse old data with the latest version of fixposition driver

**Comment by fgarciacardenas** [comment]
Hi @iamrajee. Unfortunately, for our latest stable release, we had to modify the structure of several of our I/O messages to indicate the sensor's status properly. In addition, we added several new messages (e.g., smooth odometry, ENU frame) to assist users in control tasks.

We highly recommend using the Vision-RKT2 with the latest stable release (2.85.3) to maximize compatibility, obtain the best accuracy and stability, and have access to our new tools (e.g., 3D velocity input, Ethernet recording, fleet management, PTP synchronization).

In the future, we will be careful not to break compatibility with previous releases. We are currently overhauling most of the ROS driver, and the next release will be available very soon. In this new version, adding compatibility to old messages will be very intuitive if necessary. However, I suggest simply updating the sensor and the ROS driver to the latest version.

Lastly, note that you can use our previous tags of the ROS driver, so you will always have access to this tool.
