### ISSUE TITLE
Smooth Odometry publishing

### ISSUE THREAD

**Issue by grizzi** [fixposition/fixposition_driver#52]
In the latest firmware update and documentation (2_2.85.3) we can see that there is a "smooth" odometry output available ([**FP_A-ODOMSH**](https://docs.fixposition.com/fd/what-is-the-smooth-odometry-output)). Nevertheless  I do not see in the driver the possibility of publishing  this over ROS. 

Is there any plan on supporting this feature soon? 
**EDIT**: adding minimal support in #53

**Comment by fgarciacardenas** [comment]
This information is now available on the '/fixposition/odomsh' topic.
