### ISSUE TITLE
No data 

### ISSUE THREAD

**Issue by antoniskara** [fixposition/fixposition_driver#7]
Hello ,

If RTK system does not operate then no data will be streamed to ROS. Can we take at least the GNSS data? This is a problem when there is no base station or NTRIP server in our location.

**Comment by fixposition-support** [comment]
@antoniskara The latest version has added this feature. Please check the updated README to see how to configure the Vision-RTK2 to use this together with the driver.

If you have any problems please follow up here, and if it works well for you please also let us know. 

Best rergards
